# Generated by Django 2.0.5 on 2018-05-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField(verbose_name='date')),
                ('units', models.CharField(blank=True, max_length=200, null=True, verbose_name='units')),
                ('quantity', models.IntegerField()),
                ('invoiced', models.BooleanField(default=False)),
                ('total_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Item name')),
                ('item_price', models.FloatField()),
                ('item_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Item description')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Task name ')),
            ],
        ),
    ]
