# Generated by Django 2.0.5 on 2018-05-31 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('invoices', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_sheet',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile_Employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='time_sheet',
            name='invoice',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='time_sheet',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='time_sheet',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='order',
            name='made_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile_Employee', verbose_name='Made by'),
        ),
        migrations.AddField(
            model_name='order',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile_Provider', verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='item',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile_Provider', verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile_Client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='docket',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile_Client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='docket',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='buying_entry',
            name='docket',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Docket', verbose_name='Docket'),
        ),
        migrations.AddField(
            model_name='buying_entry',
            name='invoice',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='buying_entry',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Entry_Item_Price', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='buying_entry',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='buying_entry',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile_Provider', verbose_name='Provider'),
        ),
    ]
