# Generated by Django 2.0.5 on 2018-05-20 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('invoices', '0002_auto_20180520_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Invoice number')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='invoice date')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile_Client', verbose_name='Client')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='invoice',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice', verbose_name='Invoice'),
        ),
    ]
