# Generated by Django 2.0.5 on 2018-05-29 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180529_1241'),
        ('invoices', '0002_auto_20180529_1241'),
        ('projects', '0002_auto_20180529_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='buying_entry',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Entry_Item_Price', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='buying_entry',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='buying_entry',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile_Provider', verbose_name='Provider'),
        ),
    ]
