# Generated by Django 2.0.5 on 2018-05-29 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20180527_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buying_entry',
            old_name='total_price',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='buying_entry',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Entry_Item_Price', verbose_name='Item'),
        ),
    ]
