# Generated by Django 2.0.5 on 2018-05-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20180525_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_price',
        ),
    ]
