# Generated by Django 2.0.5 on 2018-05-20 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('invoices', '0003_auto_20180520_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile_Provider', verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Units'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.FloatField(verbose_name='Item price'),
        ),
    ]
