# Generated by Django 2.0.5 on 2018-05-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20180529_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='buying_entry',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='buying_entry',
            name='units',
            field=models.CharField(blank=True, default='unidades', max_length=200, null=True, verbose_name='units'),
        ),
    ]
