# Generated by Django 2.0.5 on 2018-05-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20180522_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_sheet',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
