# Generated by Django 2.0.5 on 2018-05-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20180520_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Item description'),
        ),
    ]
