# Generated by Django 2.0.5 on 2018-05-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_auto_20180522_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_sheet',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
