# Generated by Django 2.0.5 on 2018-05-21 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_auto_20180521_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buying_entry',
            name='docket',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docket', to='invoices.Docket', verbose_name='Docket'),
        ),
        migrations.AlterField(
            model_name='buying_entry',
            name='invoice',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='invoices.Invoice', verbose_name='Invoice'),
        ),
        migrations.AlterField(
            model_name='buying_entry',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='invoices.Order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='buying_entry',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile_Provider', verbose_name='Provider'),
        ),
    ]
