# Generated by Django 2.0.5 on 2018-05-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_auto_20180522_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_sheet',
            name='coments',
            field=models.TextField(blank=True, default='coments', max_length=400, null=True, verbose_name='coments'),
        ),
    ]
