# Generated by Django 2.0.5 on 2018-05-21 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_auto_20180521_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buying_entry',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='buying_entry',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Tasks', verbose_name='Task'),
        ),
    ]
