# Generated by Django 2.0.5 on 2018-05-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_auto_20180521_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buying_entry',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
