# Generated by Django 2.0.5 on 2018-05-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_auto_20180521_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buying_entry',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
