# Generated by Django 2.0.5 on 2018-05-21 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_auto_20180521_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='docket',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buying_entry',
            name='docket',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Docket', verbose_name='Docket'),
        ),
        migrations.AlterField(
            model_name='buying_entry',
            name='invoice',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice', verbose_name='Invoice'),
        ),
        migrations.AlterField(
            model_name='buying_entry',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Order', verbose_name='Order'),
        ),
    ]
