# Generated by Django 2.0.5 on 2018-05-21 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180520_0450'),
        ('users', '0003_auto_20180521_1154'),
        ('invoices', '0012_auto_20180521_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('units', models.CharField(blank=True, max_length=200, null=True, verbose_name='units')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('invoiced', models.BooleanField(default=False)),
                ('docket', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Docket', verbose_name='Docket')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile_Employee', verbose_name='Employe')),
                ('invoice', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice', verbose_name='Invoice')),
                ('order', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Order', verbose_name='Order')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Tasks', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Time sheet',
                'verbose_name_plural': 'Time Sheets',
            },
        ),
    ]
