<<<<<<< HEAD
# Generated by Django 2.0.5 on 2018-05-31 18:18
=======
# Generated by Django 2.0.5 on 2018-05-31 18:53
>>>>>>> a0f9c3ab29d1283bd7a1af1a9b8d0fa19c3b3c91

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
