# Generated by Django 2.0.5 on 2018-05-23 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180523_1329'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='users.Profile_Client', verbose_name='Notes'),
        ),
    ]
