# Generated by Django 2.0.5 on 2018-05-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=200, null=True)),
                ('project_number', models.CharField(blank=True, max_length=200)),
                ('project_address', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('state', models.CharField(choices=[('ACT', 'Accepted'), ('WFA', 'Waiting'), ('REJ', 'Provider')], default='WFA', max_length=3)),
            ],
        ),
    ]
