# Generated by Django 2.0.5 on 2018-05-25 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180525_2232'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Code')),
                ('chapter_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Chapter name ')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, max_length=200, null=True, verbose_name='Date')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Valid untill')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Code')),
                ('task', models.CharField(blank=True, max_length=200, null=True, verbose_name='Task name ')),
                ('Chapter', models.ManyToManyField(blank=True, to='projects.Chapter', verbose_name='Chapter')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='users.Profile_Client', verbose_name='client'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_manager', to='users.Profile_Employee', verbose_name='Project manager'),
        ),
        migrations.AddField(
            model_name='project',
            name='work_force',
            field=models.ManyToManyField(blank=True, related_name='work_force', to='users.Profile_Employee', verbose_name='Resources'),
        ),
        migrations.AddField(
            model_name='scope',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Scope', verbose_name='Chapter'),
        ),
    ]
