# Generated by Django 2.0.5 on 2018-05-27 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20180527_1305'),
        ('users', '0002_auto_20180527_1305'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('chapter_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Chapter name ')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Entry name ')),
                ('code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, default='coments', max_length=400, null=True, verbose_name='Coments')),
                ('scope_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('scope_unt_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('invoice_unt_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('planif_unt_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('target_unt_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('scope_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('invoice_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('planif_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('chapter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Chapter', verbose_name='Chapter - Project')),
                ('items', models.ManyToManyField(blank=True, to='invoices.Item', verbose_name='Items')),
            ],
            options={
                'verbose_name': 'Project Entry',
                'verbose_name_plural': 'Project Entries',
            },
        ),
        migrations.CreateModel(
            name='Invoice_Meassurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coments', models.CharField(blank=True, max_length=200, null=True, verbose_name='coments')),
                ('ud_type', models.CharField(blank=True, max_length=9, null=True, verbose_name='unidades')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('wide', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_meassurement', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Entry', verbose_name='Entry')),
            ],
            options={
                'verbose_name': 'Invoice Meassurement',
                'verbose_name_plural': 'invoice Meassurements',
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_code', models.IntegerField()),
                ('phase_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Phase name ')),
                ('coments', models.TextField(blank=True, default='coments', max_length=400, null=True, verbose_name='coments')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planification_Meassurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coments', models.CharField(blank=True, max_length=200, null=True, verbose_name='coments')),
                ('ud_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='unidades')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('wide', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_meassurement', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Entry', verbose_name='Entry')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Phase', verbose_name='phase')),
            ],
            options={
                'verbose_name': 'Planification Meassurement',
                'verbose_name_plural': 'Planification Meassurements',
            },
        ),
        migrations.CreateModel(
            name='Project_Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('invoice_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('planification_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('entry', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Entry', verbose_name='Entry')),
            ],
            options={
                'verbose_name': 'Project Price',
                'verbose_name_plural': 'Project Prices',
            },
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Code')),
                ('date', models.DateField(blank=True, max_length=200, null=True, verbose_name='Date')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Valid untill')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scope_Meassurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coments', models.CharField(blank=True, max_length=200, null=True, verbose_name='coments')),
                ('ud_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='unidades')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('wide', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_meassurement', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Entry', verbose_name='Entry')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Phase', verbose_name='phase')),
            ],
            options={
                'verbose_name': 'Scope Meassurement',
                'verbose_name_plural': 'Scope Meassurements',
            },
        ),
        migrations.CreateModel(
            name='Target_Meassurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coments', models.CharField(blank=True, max_length=200, null=True, verbose_name='coments')),
                ('ud_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='unidades')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('wide', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_meassurement', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Entry', verbose_name='entry')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Phase', verbose_name='phase')),
            ],
            options={
                'verbose_name': 'Target Meassurement',
                'verbose_name_plural': 'Target Meassurements',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Code')),
                ('task_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Task name ')),
                ('description', models.TextField(blank=True, default='coments', max_length=400, null=True, verbose_name='coments')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='users.Profile_Client', verbose_name='client'),
        ),
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_manager', to='users.Profile_Employee', verbose_name='Project manager'),
        ),
        migrations.AddField(
            model_name='project',
            name='work_force',
            field=models.ManyToManyField(blank=True, related_name='work_force', to='users.Profile_Employee', verbose_name='Resources'),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('ACT', 'Accepted'), ('WFA', 'Waiting'), ('REJ', 'Overruled')], default='WFA', max_length=3),
        ),
        migrations.AddField(
            model_name='scope',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='project_price',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='invoice_meassurement',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Phase', verbose_name='phase'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Scope', verbose_name='Scope'),
        ),
    ]
