# Generated by Django 2.0.5 on 2018-05-31 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20180531_1828'),
        ('users', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Scope', verbose_name='Scope'),
        ),
        migrations.AddField(
            model_name='entry',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Chapter', verbose_name='Chapter - Project'),
        ),
        migrations.AddField(
            model_name='entry',
            name='items',
            field=models.ManyToManyField(blank=True, to='invoices.Item', verbose_name='Items'),
        ),
        migrations.AddField(
            model_name='entry',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='entry_item_price',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Chapter', verbose_name='Chapter'),
        ),
        migrations.AddField(
            model_name='entry_item_price',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Entry', verbose_name='Entry'),
        ),
        migrations.AddField(
            model_name='entry_item_price',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Item', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='entry_item_price',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='invoice_meassurement',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Entry', verbose_name='Entry'),
        ),
        migrations.AddField(
            model_name='invoice_meassurement',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Phase', verbose_name='phase'),
        ),
        migrations.AddField(
            model_name='planification_meassurement',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Entry', verbose_name='Entry'),
        ),
        migrations.AddField(
            model_name='planification_meassurement',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Phase', verbose_name='phase'),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='users.Profile_Client', verbose_name='client'),
        ),
        migrations.AddField(
            model_name='project',
            name='foreman',
            field=models.ManyToManyField(blank=True, related_name='foreman', to='users.Profile_Employee', verbose_name='Foreman'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ManyToManyField(blank=True, related_name='project_manager', to='users.Profile_Employee', verbose_name='Project manager'),
        ),
        migrations.AddField(
            model_name='project',
            name='quantity_surveyor',
            field=models.ManyToManyField(blank=True, related_name='quantity_surveyor', to='users.Profile_Employee', verbose_name='quantyty surveyor'),
        ),
        migrations.AddField(
            model_name='project',
            name='site_manager',
            field=models.ManyToManyField(blank=True, related_name='site_manager', to='users.Profile_Employee', verbose_name='site manager'),
        ),
    ]
