# Generated by Django 2.0.5 on 2018-05-20 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='users.Profile_Client', verbose_name='client'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_manager', to='users.Profile_Employee', verbose_name='Project manager'),
        ),
        migrations.AddField(
            model_name='project',
            name='work_force',
            field=models.ManyToManyField(blank=True, related_name='work_force', to='users.Profile_Employee', verbose_name='Resources'),
        ),
    ]
