# Generated by Django 2.0.5 on 2018-05-31 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180531_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry_item_price',
            name='chapter',
        ),
    ]
