# Generated by Django 2.0.5 on 2018-05-27 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_entry_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Chapter', verbose_name='Chapter - Project'),
        ),
    ]
