# Generated by Django 2.0.5 on 2018-05-27 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180527_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='chapter',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Chapter', verbose_name='Chapter'),
        ),
    ]
