# Generated by Django 2.0.5 on 2018-05-26 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180526_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Scope', verbose_name='Scope'),
        ),
    ]
