# Generated by Django 2.0.5 on 2018-05-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180527_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='invoice_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
