# Generated by Django 2.0.5 on 2018-05-26 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180526_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_code', models.IntegerField()),
                ('phase_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Phase name ')),
                ('coments', models.TextField(blank=True, default='coments', max_length=400, null=True, verbose_name='coments')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Phase', verbose_name='Scope'),
        ),
    ]
