# Generated by Django 2.0.5 on 2018-05-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180527_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_meassurement',
            name='coments',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='coments'),
        ),
        migrations.AlterField(
            model_name='invoice_meassurement',
            name='ud_type',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='unidades'),
        ),
    ]
