# Generated by Django 2.0.5 on 2018-05-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180527_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='planification_meassurement',
            name='coments',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='coments'),
        ),
        migrations.AddField(
            model_name='scope_meassurement',
            name='coments',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='coments'),
        ),
        migrations.AddField(
            model_name='target_meassurement',
            name='coments',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='coments'),
        ),
    ]
