# Generated by Django 2.0.5 on 2018-05-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_entry_invoice_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='scope_unt_price',
            new_name='unit_price',
        ),
    ]
