# Generated by Django 2.0.5 on 2018-05-26 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_task_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope_Meassurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ud_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='unidades')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('wide', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_measurement', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='scope',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Phase', verbose_name='phase'),
        ),
        migrations.AlterField(
            model_name='task',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Phase', verbose_name='phase'),
        ),
    ]
