# Generated by Django 2.0.5 on 2018-05-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20180528_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='traget_quantity',
            new_name='target_quantity',
        ),
    ]
