# Generated by Django 2.0.5 on 2018-05-26 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20180526_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope_meassurements',
            old_name='total_measurement',
            new_name='total_meassurement',
        ),
    ]
