# Generated by Django 2.0.5 on 2018-06-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20180602_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='units',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Units'),
        ),
    ]
