# Generated by Django 2.0.5 on 2018-05-26 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20180526_0202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope_meassurements',
            old_name='quantity',
            new_name='units',
        ),
    ]
