# Generated by Django 2.0.5 on 2018-05-28 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20180528_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry_item_price_target',
            old_name='price',
            new_name='price_per_unt',
        ),
        migrations.RemoveField(
            model_name='entry_item_price_target',
            name='project',
        ),
        migrations.AddField(
            model_name='entry_item_price_target',
            name='quantity_per_unt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='entry_item_price_target',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='entry_item_price_target',
            name='total_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='invoice_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='planif_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='real_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='scope_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='entry_item_price_target',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Entry', verbose_name='Project'),
        ),
    ]
