# Generated by Django 2.0.5 on 2018-05-26 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20180526_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='task',
            name='quantity',
        ),
        migrations.AddField(
            model_name='scope_meassurements',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Phase', verbose_name='phase'),
        ),
        migrations.AddField(
            model_name='scope_meassurements',
            name='task',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.Task', verbose_name='task'),
        ),
    ]
