# Generated by Django 2.0.5 on 2018-05-26 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20180526_0347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Chapter',
            new_name='chapter',
        ),
    ]
