# Generated by Django 2.0.5 on 2018-05-29 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20180528_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry_item_price_target',
            old_name='quantity_per_unt',
            new_name='quantity_per_entry',
        ),
        migrations.RemoveField(
            model_name='entry_item_price_target',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='entry_item_price_target',
            name='total_quantity',
        ),
        migrations.AddField(
            model_name='entry_item_price_target',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Chapter', verbose_name='Chapter'),
        ),
        migrations.AddField(
            model_name='entry_item_price_target',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='entry_item_price_target',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Entry', verbose_name='Entry'),
        ),
        migrations.AlterField(
            model_name='entry_item_price_target',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Item', verbose_name='Item'),
        ),
    ]
