# Generated by Django 2.0.5 on 2018-06-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20180603_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry_item_price',
            name='quantity_per_entry_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Quantity per Entry Estimated'),
        ),
        migrations.AlterField(
            model_name='entry_item_price',
            name='quantity_per_entry_unit_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Quantity per entry Actual'),
        ),
        migrations.AlterField(
            model_name='entry_item_price',
            name='quantity_per_entry_unit_scope',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Quantity per Entry Estimated'),
        ),
    ]
