# Generated by Django 2.0.5 on 2018-06-03 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20180603_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry_item_price',
            name='quantity_per_entry_unit_scope',
        ),
    ]
