# Generated by Django 2.0.5 on 2018-05-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20180526_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='phase',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='coments', max_length=400, null=True, verbose_name='coments'),
        ),
    ]
