# Generated by Django 2.0.5 on 2018-05-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20180529_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry_item_price_target',
            old_name='price_per_unt',
            new_name='item_price',
        ),
        migrations.RenameField(
            model_name='entry_item_price_target',
            old_name='quantity_per_entry',
            new_name='price_per_entry_un',
        ),
        migrations.AddField(
            model_name='entry_item_price_target',
            name='quantity_per_entry_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
