# Generated by Django 2.0.5 on 2018-05-29 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20180529_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry_item_price_target',
            old_name='price_per_entry_un',
            new_name='price_per_entry_unit',
        ),
    ]
