# Generated by Django 2.0.5 on 2018-05-26 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20180526_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='chapter',
        ),
    ]
