# Generated by Django 2.0.5 on 2018-06-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_entry_item_price_quantity_per_entry_unit_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry_item_price',
            name='item_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Item Price'),
        ),
        migrations.AlterField(
            model_name='entry_item_price',
            name='item_price_scope',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Item Price[Scope]'),
        ),
        migrations.AlterField(
            model_name='entry_item_price',
            name='price_per_entry_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Price/Entry Unit'),
        ),
        migrations.AlterField(
            model_name='entry_item_price',
            name='price_per_entry_unit_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Price/Entry Unit[Actual]'),
        ),
        migrations.AlterField(
            model_name='entry_item_price',
            name='price_per_entry_unit_scope',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Price/Entry[Scope]'),
        ),
        migrations.AlterField(
            model_name='entry_item_price',
            name='quantity_bought',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Quantity_Bought'),
        ),
        migrations.AlterField(
            model_name='entry_item_price',
            name='quantity_needed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Estimated Quantity Needed'),
        ),
        migrations.AlterField(
            model_name='entry_item_price',
            name='quantity_per_entry_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Quantity/Entry[Estimated]'),
        ),
        migrations.AlterField(
            model_name='entry_item_price',
            name='quantity_per_entry_unit_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Quantity/Entry[Actual]'),
        ),
    ]
