# Generated by Django 2.0.5 on 2018-06-03 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20180603_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='custom_factor',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='general_cost_factor',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='indirect_cost_factor',
        ),
        migrations.AddField(
            model_name='project',
            name='custom_factor',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='general_cost_factor',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='indirect_cost_factor',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='entry_item_price',
            name='item_price_scope',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Item Price [Scope]'),
        ),
        migrations.AlterField(
            model_name='entry_item_price',
            name='price_per_entry_unit_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Price/Entry Unit [Actual]'),
        ),
        migrations.AlterField(
            model_name='entry_item_price',
            name='price_per_entry_unit_scope',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Price/Entry Unit [Scope]'),
        ),
        migrations.AlterField(
            model_name='entry_item_price',
            name='quantity_per_entry_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Quantity/Entry [Estimated]'),
        ),
        migrations.AlterField(
            model_name='entry_item_price',
            name='quantity_per_entry_unit_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Quantity/Entry [Actual]'),
        ),
        migrations.AlterField(
            model_name='entry_item_price',
            name='scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Scope', verbose_name='Scope'),
        ),
    ]
