# Generated by Django 2.0.5 on 2018-05-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20180529_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry_item_price',
            name='quantity_needed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
