# Generated by Django 2.0.5 on 2018-05-29 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_entry_item_price_quantity_needed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['code']},
        ),
    ]
