# Generated by Django 2.0.5 on 2018-05-26 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_scope_meassurements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope_meassurements',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Task', verbose_name='task'),
        ),
    ]
