# Generated by Django 2.0.5 on 2018-05-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180527_1250'),
        ('projects', '0016_auto_20180529_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Code')),
                ('task_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Task name ')),
                ('description', models.TextField(blank=True, default='coments', max_length=400, null=True, verbose_name='coments')),
            ],
        ),
        migrations.RenameField(
            model_name='entry_item_price',
            old_name='quantity_per_entry_unit',
            new_name='quantity_per_entry_unit_real',
        ),
        migrations.RemoveField(
            model_name='project',
            name='work_force',
        ),
        migrations.AddField(
            model_name='entry_item_price',
            name='quantity_per_entry_unit_scope',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='foreman',
            field=models.ManyToManyField(blank=True, related_name='foreman', to='users.Profile_Employee', verbose_name='Foreman'),
        ),
        migrations.AddField(
            model_name='project',
            name='quantity_surveyor',
            field=models.ManyToManyField(blank=True, related_name='quantity_surveyor', to='users.Profile_Employee', verbose_name='quantyty surveyor'),
        ),
        migrations.AddField(
            model_name='project',
            name='site_manager',
            field=models.ManyToManyField(blank=True, related_name='site_manager', to='users.Profile_Employee', verbose_name='site manager'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_manager',
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ManyToManyField(blank=True, related_name='project_manager', to='users.Profile_Employee', verbose_name='Project manager'),
        ),
    ]
