# Generated by Django 2.0.5 on 2018-05-26 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20180526_0546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope_meassurements',
            old_name='units',
            new_name='quantity',
        ),
    ]
