# Generated by Django 2.0.5 on 2018-06-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20180603_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='benefit_factor',
        ),
        migrations.AddField(
            model_name='project',
            name='benefit_factor',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=20, null=True),
        ),
    ]
