# Generated by Django 2.0.5 on 2018-06-03 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20180603_0252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry_item_price',
            old_name='scope',
            new_name='project',
        ),
    ]
