# Generated by Django 2.0.5 on 2018-05-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20180529_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry_item_price',
            name='quantity_per_entry_unit_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='real'),
        ),
        migrations.AlterField(
            model_name='entry_item_price',
            name='quantity_per_entry_unit_scope',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='scope'),
        ),
    ]
