# Generated by Django 2.0.5 on 2018-05-26 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20180525_2232'),
        ('projects', '0017_auto_20180526_0611'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Tasks',
        ),
    ]
