# Generated by Django 2.0.5 on 2018-05-26 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20180525_2232'),
        ('projects', '0018_auto_20180526_0651'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
