# Generated by Django 2.0.5 on 2018-06-03 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20180603_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='benefit_factor',
            new_name='risk_factor',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='custom_factor',
        ),
    ]
