# Generated by Django 2.0.5 on 2018-05-26 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_invoice_meassurements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoice_Meassurements',
            new_name='Invoice_Meassurement',
        ),
        migrations.RenameModel(
            old_name='Scope_Meassurements',
            new_name='Scope_Meassurement',
        ),
    ]
