# Generated by Django 2.0.5 on 2018-05-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20180530_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry_item_price',
            name='quantity_bought',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Estimated quantity needed'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='total_price_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Actual chapter price'),
        ),
        migrations.AlterField(
            model_name='entry_item_price',
            name='price_per_entry_unit_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Actual Price per Entry unit'),
        ),
        migrations.AlterField(
            model_name='entry_item_price',
            name='quantity_needed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Estimated quantity needed'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='real_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Actual price'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='total_price_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Construction actual Price'),
        ),
    ]
