# Generated by Django 2.0.5 on 2018-05-26 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20180526_0730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice_meassurement',
            options={'verbose_name': 'Invoice Meassurement', 'verbose_name_plural': 'invoice Meassurements'},
        ),
        migrations.AlterModelOptions(
            name='scope_meassurement',
            options={'verbose_name': 'Scope Meassurement', 'verbose_name_plural': 'Scope Meassurements'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='total_price',
        ),
    ]
