# Generated by Django 2.0.5 on 2018-06-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('projects', '0021_auto_20180603_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_manager',
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ManyToManyField(blank=True, related_name='project_manager', to='users.Profile_Employee', verbose_name='Project manager'),
        ),
    ]
