# Generated by Django 2.0.5 on 2018-06-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20180603_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='invoice_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='autocalculated field', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='planif_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='autocalculated field', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='scope_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='autocalculated field', max_digits=20, null=True),
        ),
    ]
