# Generated by Django 2.0.5 on 2018-06-08 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20180606_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='units',
            field=models.CharField(default='Unt', max_length=200, verbose_name='Chapter name '),
        ),
        migrations.AlterField(
            model_name='planification_meassurement',
            name='Indirect_Cost_Entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Indirect_Cost_Entry', verbose_name='Entry'),
        ),
        migrations.AlterField(
            model_name='scope_meassurement',
            name='Indirect_Cost_Entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Indirect_Cost_Entry', verbose_name='Entry'),
        ),
        migrations.AlterField(
            model_name='target_meassurement',
            name='Indirect_Cost_Entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Indirect_Cost_Entry', verbose_name='Entry'),
        ),
    ]
