# Generated by Django 2.0.5 on 2018-05-26 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_target_meassurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target_meassurement',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Task', verbose_name='task'),
        ),
    ]
