# Generated by Django 2.0.5 on 2018-05-26 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20180526_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_meassurement',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Task', verbose_name='task'),
        ),
        migrations.AlterField(
            model_name='planification_meassurement',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Task', verbose_name='task'),
        ),
        migrations.AlterField(
            model_name='scope_meassurement',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Task', verbose_name='task'),
        ),
    ]
