# Generated by Django 2.0.5 on 2018-06-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20180609_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='foreman',
            field=models.ManyToManyField(blank=True, related_name='foreman', to='users.Profile_Employee', verbose_name='Foreman'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ManyToManyField(blank=True, related_name='project_manager', to='users.Profile_Employee', verbose_name='Project manager'),
        ),
        migrations.AlterField(
            model_name='project',
            name='quantity_surveyor',
            field=models.ManyToManyField(blank=True, related_name='quantity_surveyor', to='users.Profile_Employee', verbose_name='quantyty surveyor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='site_manager',
            field=models.ManyToManyField(blank=True, related_name='site_manager', to='users.Profile_Employee', verbose_name='site manager'),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('ACT', 'Accepted'), ('WFA', 'Waiting'), ('REJ', 'Overruled')], default='WFA', max_length=3, null=True),
        ),
    ]
