# Generated by Django 2.0.5 on 2018-05-26 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20180526_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('invoice_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('planification_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Project')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'Project Price',
                'verbose_name_plural': 'Project Prices',
            },
        ),
    ]
