# Generated by Django 2.0.5 on 2018-06-09 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_remove_entry_item_price_price_per_entry_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry_item_price',
            old_name='quantity_per_entry_unit',
            new_name='quantity_per_entry_unit_scope',
        ),
    ]
