# Generated by Django 2.0.5 on 2018-06-10 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_auto_20180609_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='quantity',
            new_name='quantity_scope',
        ),
    ]
