# Generated by Django 2.0.5 on 2018-06-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_auto_20180610_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry_item_price',
            name='quantity_per_entry_unit_target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Quantity/Entry [Target]'),
        ),
        migrations.AlterField(
            model_name='entry_item_price',
            name='quantity_per_entry_unit_scope',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Quantity/Entry [Estimated]'),
        ),
    ]
