# Generated by Django 2.0.5 on 2018-06-14 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_auto_20180610_0124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope_meassurement',
            old_name='Indirect_Cost_Entry',
            new_name='indirect_cost_entry',
        ),
    ]
