# Generated by Django 2.0.5 on 2018-06-16 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_auto_20180616_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope_meassurement',
            name='high',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='wide', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='scope_meassurement',
            name='phase',
            field=models.ForeignKey(default=1, help_text='phase', on_delete=django.db.models.deletion.CASCADE, to='projects.Phase', verbose_name='phase'),
        ),
        migrations.AlterField(
            model_name='scope_meassurement',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='width', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='scope_meassurement',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='high', max_digits=20, null=True),
        ),
    ]
