# Generated by Django 2.0.5 on 2018-06-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_auto_20180616_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope_meassurement',
            options={'ordering': ['id'], 'verbose_name': 'Scope Meassurement', 'verbose_name_plural': 'Scope Meassurements'},
        ),
        migrations.AddField(
            model_name='scope_meassurement',
            name='location',
            field=models.CharField(blank=True, help_text='location', max_length=10, null=True, verbose_name='coments'),
        ),
    ]
