# Generated by Django 2.0.5 on 2018-05-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_client',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='profile_client',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='profile_client',
            name='project',
        ),
        migrations.RemoveField(
            model_name='profile_client',
            name='quotes',
        ),
        migrations.AddField(
            model_name='profile_employee',
            name='hour_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='profile_employee',
            name='hour_price_int',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile_provider',
            name='company_name',
            field=models.CharField(blank=True, default='Introduce company name', max_length=30),
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
