# Generated by Django 2.0.5 on 2018-05-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180521_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_employee',
            name='hour_price_int',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
