# Generated by Django 2.0.5 on 2018-05-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180522_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_employee',
            name='hour_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
