# Generated by Django 2.0.5 on 2018-05-23 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180522_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_client',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='profile_client',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='profile_client',
            name='quotes',
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
