# Generated by Django 2.0.5 on 2018-05-25 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180523_1329'),
        ('users', '0006_auto_20180523_1348'),
    ]

    operations = [
    ]
