# Generated by Django 2.0.5 on 2018-06-02 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0002_auto_20180531_1853'),
        ('projects', '0007_auto_20180602_1120'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price_Solicitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Code')),
                ('date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('items', models.ManyToManyField(blank=True, to='invoices.Item', verbose_name='Items')),
                ('made_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile_Employee', verbose_name='Made by')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Project')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile_Provider', verbose_name='Provider')),
            ],
        ),
        migrations.CreateModel(
            name='solicitude_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(blank=True, default='units', max_length=200, null=True, verbose_name='units')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Item', verbose_name='Item')),
                ('price_solicitude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.Price_Solicitude', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Solicitude of prices',
                'verbose_name_plural': 'Solicitude of prices',
            },
        ),
    ]
