# Generated by Django 2.0.5 on 2018-06-02 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price_solicitude',
            name='total_price',
        ),
    ]
