# Generated by Django 2.0.5 on 2018-06-02 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_remove_price_solicitude_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitude_entry',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Entry_Item_Price', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='solicitude_entry',
            name='price_solicitude',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.Price_Solicitude', verbose_name='price_solicitude'),
        ),
    ]
