# Generated by Django 2.0.5 on 2018-06-02 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_auto_20180602_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitude_entry',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Entry_Item_Price', unique=True, verbose_name='Item'),
        ),
    ]
