<<<<<<< HEAD
# Generated by Django 2.0.5 on 2018-05-31 18:18
=======
# Generated by Django 2.0.5 on 2018-06-01 13:54
>>>>>>> a0f9c3ab29d1283bd7a1af1a9b8d0fa19c3b3c91

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('DRG', 'Drawing'), ('IMG', 'Imagen'), ('QOT', 'Quote'), ('INV', 'Ivoice'), ('ENG', 'Egineer')], default='IMG', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
