# Generated by Django 2.0.5 on 2018-05-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='document_type',
        ),
        migrations.DeleteModel(
            name='Document_Type',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
