# Generated by Django 2.0.5 on 2018-05-27 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_auto_20180527_1250'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document_manager', '0002_auto_20180527_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('DRG', 'Drawing'), ('IMG', 'Imagen'), ('QOT', 'Quote'), ('INV', 'Ivoice'), ('ENG', 'Egineer')], default='IMG', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Document number')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document_manager.Document_Type', verbose_name='Document type')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Project')),
                ('uploaded_by', models.ForeignKey(default='uploader', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='uploader')),
            ],
        ),
    ]
